---
name: beam
github_org: apache
repository: beam
merge_branch: master
verification_branch: master
scm_type: github
jenkins_location: https://builds.apache.org
verification_job_name: beam_PreCommit_Merge
