--- !MergeBotConfig
name: beam-website
proj_name: beam
github_org: apache
repository: beam-site
merge_branch: asf-site
verification_branch: mergebot
scm_type: github
jenkins_location: https://builds.apache.org
prepare_command: "bundle exec jekyll build && git add --all -- content"
verification_job_name: beam_PreCommit_Site_Merge
